spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171
  
server:
  port: 8088
  
logging:
  file: /Users/dd/Documents/work/tmp/logs/100003171/apollo-configservice.log
